# physics
nu = 1.0e-4 # kinetic viscosity
# CFD
dt = 1.0e-3 # time step size
dkx = 0.5 # Lx=2*pi/dkx
dkz = 1.0 # Lz=2*pi/dkx
NX = 640 # number of cells in x direction
NY = 288 # number of cells in y direction
NZ = 640 # number of cells in z direction
alpha_mesh = 2.4 # the de-sigularity size of mesh y=tanh(alpha eta)/tanh(alpha)
NT = 500000 # number of time steps
initial_condition = 1 # 1 - "laminar only", 2 - "laminar perturbation", 3 - "renewal"
# MPI
PX = 32  # number of processors in x direction
PZ = 16 # number of processors in z direction
# IO
save_interval = 500 # save results every $(save_interval) time steps
